name: Run E2E tests

on: [pull_request]

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Setup xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends xvfb

      - name: Run xvfb
        run: |
          npm run build
          xvfb-run -a npm run e2e
